// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchEngine.Infrastructure.Data;

#nullable disable

namespace SearchEngine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EngineContext))]
    partial class EngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchEngine.Domain.Entities.UrlPageRank", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rank")
                        .HasColumnType("float");

                    b.HasKey("Url");

                    b.ToTable("UrlPageRanks");
                });

            modelBuilder.Entity("SearchEngine.Domain.Entities.WordsToUrl", b =>
                {
                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Word");

                    b.ToTable("WordsToURLs");
                });
#pragma warning restore 612, 618
        }
    }
}
